fork: true
repo_slug: vszakats/harbour-core
site_slug: vszakats/harbour-core
site_branch_and_root: master/docs/
dl_url: https://github.com/vszakats/harbour-core/releases
badge_version: "3.4"
baseurl: /harbour-core

example_categories:
  - basic
  - arrays
  - database
  - extensions
  - web
collections:
  example:
    output: true
defaults:
  - scope:
      path: ""
      type: example
    values:
      layout: example

incremental: true
exclude: ["node_modules"]
sass:
  style: compressed
